if: branch =~ ^master$|^development$
language: python
group: stable
dist: trusty
os: linux
sudo: required
services:
- docker

cache: pip

before_script: |-
  sudo /etc/init.d/mysql stop && docker-compose up -d

  # run 10 times; sleep 1 sec each; when socket ok, exit 0, if not, wait 1 sec
  for run in {1..10}; do nc -nv -w 1 127.0.0.1 3006 && exit 0 || sleep 1 ; done

script: |-
  yarn test:server